app/student/forms.py
from flask_wtf import FlaskForm  # FlaskForm为表单基类
from wtforms import validators
from wtforms.fields import SubmitField, StringField, PasswordField, SelectField, RadioField, DateTimeField, BooleanField
from wtforms.validators import DataRequired, EqualTo, Email, Regexp, ValidationError, InputRequired
from app.models import Student, db, Class


class SelectField2(SelectField):

    def pre_validate(self, form):
        pass


class LoginForm(FlaskForm):
    username = StringField(
        label="用户名",
        validators=[
            DataRequired("请输入用户名！")
        ],
        description="用户名",
        render_kw={
            "class": "form-control",
            "id": "username",
            "placeholder": "请输入用户名！",
            "required": 'required',  # 表示此项不能为空
            "autofocus": "autofocus",
        }
    )
    pwd = PasswordField(
        label="密码",
        validators=[
            DataRequired("请输入密码！")
        ],
        description="密码",
        render_kw={
            "class": "form-control",
            "id": "password",
            "placeholder": "请输入密码！",
            "required": 'required',  # 表示此项不能为空
            "autofocus": "autofocus",
        }
    )
    submit = SubmitField(
        '登录',
        render_kw={
            "class": "btn btn-info",
        }
    )


class RegisterForm(FlaskForm):
    username = StringField(
        label="用户名",
        validators=[
            InputRequired(message="请输入用户名！")
        ],
        description="用户名",
        render_kw={
            "class": "form-control",
            "placeholder": "请输入用户名！",
            "required": 'required',  # 表示此项不能为空
            "autofocus": "autofocus",
        }
    )

    sex = RadioField(
        label="性别",
        choices=(('0', '男'), ('1', '女')),
        description="性别",
        render_kw={
            "class": "form-control",
            "placeholder": "请选择性别！",
            "required": 'required',  # 表示此项不能为空
            "autofocus": "autofocus",
        },

    )

    pwd = PasswordField(
        label="密码",
        validators=[InputRequired(message="请输入密码！")],
        description="密码",
        render_kw={
            "class": "form-control",
            "placeholder": "请输入密码！",
            "required": 'required',  # 表示此项不能为空
            "autofocus": "autofocus",
        }
    )
    repwd = PasswordField(
        label="确认密码",
        validators=[InputRequired(message="请输入确认密码！"), EqualTo('pwd', message="两次密码不一致！")],
        description="确认密码",
        render_kw={
            "class": "form-control",
            "placeholder": "请输入确认密码！",
            "required": 'required',  # 表示此项不能为空
            "autofocus": "autofocus",
        }
    )
    email = StringField(
        label="邮箱",
        validators=[InputRequired(message="请输入邮箱！"), Email(message="邮箱格式不正确！")],
        description="邮箱",
        render_kw={
            "class": "form-control",
            "placeholder": "请输入邮箱！",
            "required": 'required',  # 表示此项不能为空
            "autofocus": "autofocus",
        }
    )
    name = StringField(
        label="姓名",
        validators=[InputRequired(message="请输入姓名！")],
        description="姓名",
        render_kw={
            "class": "form-control",
            "placeholder": "请输入姓名！",
            "required": 'required',  # 表示此项不能为空
            "autofocus": "autofocus",
        }
    )
    phone = StringField(
        label="手机号码",
        validators=[InputRequired(message="请输入手机号码！"), Regexp("1[3589]\\d{9}", message="手机号码格式不正确！")],
        description="手机号码",
        render_kw={
            "class": "form-control",
            "placeholder": "请输入手机号码！",
            "required": 'required',  # 表示此项不能为空
            "autofocus": "autofocus",
        }
    )
    sid = StringField(
        label="学号",
        validators=[InputRequired(message="请输入学号！")],
        description="学号",
        render_kw={
            "class": "form-control",
            "placeholder": "请输入学号！",
            "required": 'required',  # 表示此项不能为空
            "autofocus": "autofocus",
        }
    )

    l_cls = [(cls.id, cls.name) for cls in db.session.query(Class).all()]

    cls = SelectField2(
        coerce=str,
        label="班级",
        validators=[DataRequired('请选择班级')],
        choices=tuple(l_cls),
        render_kw={
            'class': 'form-control',
            "placeholder": "请选择班级！",
            "required": 'required',  # 表示此项不能为空
        },
    )
    birthday = DateTimeField(
        label="生日",
        validators=[InputRequired(message="请选择生日！")],
        description="生日",
        render_kw={
            "class": "form-control",
            "placeholder": "请选择生日！",
            "autofocus": "autofocus",
        }
    )
    date_in = DateTimeField(
        label="入学时间",
        validators=[InputRequired(message="请选择入学时间！")],
        description="入学时间",
        render_kw={
            "class": "form-control",
            "placeholder": "请选择入学时间！",
            "autofocus": "autofocus",
        }
    )
    agree = BooleanField('是否同意服务条件和隐私策略！', [validators.InputRequired()])

    def validate_name(self, field):
        username = field.data
        user = Student.query.filter_by(username=username).count()
        if user == 1:
            raise ValidationError("用户名已经存在！")

    def validate_email(self, field):
        email = field.data
        user = Student.query.filter_by(email=email).count()
        if user == 1:
            raise ValidationError("邮箱已经存在！")

    def validate_phone(self, field):
        phone = field.data
        user = Student.query.filter_by(phone=phone).count()
        if user == 1:
            raise ValidationError("手机号码已经存在！")

    def validate_sid(self, field):
        sid = field.data
        user = Student.query.filter_by(id=sid).count()
        if user == 1:
            raise ValidationError("学号已经存在！")


class SignForm(FlaskForm):
    unit = StringField(
        label="章节",
        validators=[
            DataRequired("请输入章节！"),
            Regexp(r'.+', message="请输入章节")
        ],
        description="章节",
        render_kw={
            "class": "form-control",
            "style": "width: 150px;height: 10px",
            "placeholder": "请输入章节！",
        }
    )
    v_num = StringField(
        label="视频号",
        validators=[
            DataRequired("请输入视频号！"),
            Regexp(r'^[1-9]\d*$', message="请输入视频号（数值型.例如:10,代表第10个视频。）")
        ],
        description="章节",
        render_kw={
            "class": "form-control",
            "style": "width: 150px;height: 10px",
            "placeholder": "请输入视频号！",
            "required": 'required',  # 表示此项不能为空
            # "required": False,  # 设置后，前端页面不进行required是否为空的校验。即点击提交后显示“请填写此字段！”不再显示
        }
    )
    code_num = StringField(
        label="章节",
        validators=[
            DataRequired("请输入代码数！"),
            Regexp(r'.+', message="请输入代码行数（数值型.例如:100，代表100行代码。）")
        ],
        description="代码数",
        render_kw={
            "class": "form-control",
            "style": "width: 150px;height: 10px",
            "placeholder": "请输入代码数！",
            "required": 'required',  # 表示此项不能为空
        }
    )

app/student/__init__.py
from flask import Blueprint

student = Blueprint("student", __name__)

import app.student.views

app/student/views.py
import time
import uuid

from functools import wraps
from flask import render_template, redirect, url_for, session, request
from wtforms.validators import ValidationError
from werkzeug.security import generate_password_hash
from . import student
from app import db, app
from app.models import Student, Class, Sign
from app.student.forms import LoginForm, RegisterForm, SignForm



# 登陆装饰器
def user_login_req(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if 'username' not in session:
            return redirect(url_for("student.login", next=request.url))
        return f(*args, **kwargs)

    return decorated_function


@app.route('/')
def hello_world():
    return redirect(url_for('student.login'))


# 登录
@student.route("/login/", methods=["GET", "POST"])
def login():
    form = LoginForm()
    # 通过session获取 error_message
    error_message = session.get('error_message')
    session["error_message"] = None

    if request.method == "POST":
        data = form.data
        user = Student.query.filter_by(username=data["username"]).first()

        if not user:
            error_message = "用户名不存在！"
            session["error_message"] = error_message
            return redirect(url_for("student.login"))
        if not user.check_pwd(data["pwd"]):
            error_message = "密码错误！"
            session["error_message"] = error_message
            return redirect(url_for("student.login"))

        session["username"] = user.username
        return redirect(url_for("student.sign"))

    return render_template("student/login.html", form=form, error_message=error_message)


# 登出
@student.route('/logout/')
def logout():
    session["username"] = None
    return redirect(url_for("student.login"))


# 注册
@student.route("/register/", methods=["GET", "POST"])
def register():
    form = RegisterForm()
    classes = Class.query.all()

    if request.method == "POST":
        # 获取数据
        form = RegisterForm(request.form)

        try:
            form.validate_name(form.username)
            form.validate_email(form.email)
            form.validate_phone(form.phone)
            form.validate_sid(form.sid)
        except ValidationError as e:
            context = {
                'err': None,
                'err2': e,
            }
            err2 = None
            return render_template("student/register.html", form=form, **context)

        if form.validate():
            data = form.data
            stu = Student(
                id=data["sid"],
                username=data["username"],
                name=data["name"],
                sex=data["sex"],
                pwd=generate_password_hash(data["pwd"]),
                cid=data["cls"],
                email=data["email"],
                phone=data["phone"],
                birthday=data["birthday"],
                date_in=data["date_in"],
                uuid=uuid.uuid4().hex
            )
            db.session.add(stu)
            db.session.commit()
            return render_template("student/register_ok.html")

    err = form.errors
    context = {
        'err': err,
        'err2': None,
    }
    err = None
    return render_template("student/register.html", form=form, classes=classes, **context)


# 查看所有班级
@student.route("/class/")
def all_class():
    data = Class.query.all()
    return render_template("student/class.html", data=data)


# 忘记密码
@student.route("/reset_password/")
def reset_password():
    pass
    # data = Class.query.all()
    # return render_template("student/forgot-password.html", data=data)


# 学生签到页面
@student.route("/sign/", methods=["GET", "POST"])
@student.route("/sign/<int:page>", methods=["GET", "POST"])
@user_login_req
def sign(page=1):
    form = SignForm()
    username = session.get("username")
    user = Student.query.filter_by(username=username).first()
    datetime = time.strftime('%Y-%m-%d %H:%M:%S')
    sid = user.id
    sign = Sign.query.filter_by(sid=sid).all()
    pager = Sign.query.filter_by(sid=sid).paginate(page, 10)

    if request.method == "GET":

        context = {
            'form': form,
            'user': user,
            'sign': sign,
            'datetime': datetime,
            'sign_count': len(sign),
            'pager': pager,
        }

        return render_template("student/sign.html", **context)

    elif request.method == "POST":
        form = SignForm(request.form)
        data = form.data

        do_sign = Sign(
            sid=sid,
            unit=data["unit"],
            v_num=data["v_num"],
            code_num=data["code_num"],
            operation=True
        )
        db.session.add(do_sign)
        db.session.commit()
        return redirect(url_for("student.sign"))


# **************************************** 测试Ajax用 ******************************************
# 注册--Ajax校验版
from flask import jsonify


@app.route("/userValid/", methods=['GET', 'POST'])
def userValid():
    # 定义json字典数据格式
    result = {
        "code": "",
        "data": ""
    }
    if request.method == "POST":
        # 获取ajax请求中的参数
        username = request.args.get("username")
        if username:
            # 查询数据库有无这个用户
            user = Student.query.filter_by(username=username).first()
            if user:
                result["code"] = 400
                result["data"] = "用户名已存在"
            else:
                result["code"] = 200
                result["data"] = "用户名未被注册，可以使用"
        return jsonify(result)

app/templates/student/class.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>all classes</title>
</head>
<body>
<table border="1" width="500px" cellspacing="0">
    <tr>
        <th>ID</th>
        <th>班级名称</th>
    </tr>
    {% for i in data %}
        <tr>
            <td>{{ i.id }}</td>
            <td>{{ i.name }}</td>
        </tr>
    {% endfor %}
</table>

</body>
</html>

app/templates/student/forgot-password.html
<!DOCTYPE html>
<head>
	<title>Forgot Password</title>
	<meta name="keywords" content="" />
	<meta name="description" content="" />
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<link href="{{ url_for('static',filename="student/css/font-awesome.min.css") }}" rel="stylesheet" type="text/css">
	<link href="{{ url_for('static',filename="student/css/bootstrap.min.css") }}" rel="stylesheet" type="text/css">
	<link href="{{ url_for('static',filename="student/css/bootstrap-theme.min.css") }}" rel="stylesheet" type="text/css">
	<link href="{{ url_for('static',filename="student/css/templatemo_style.css") }}" rel="stylesheet" type="text/css">
</head>
<body class="templatemo-bg-gray">
	<div class="container">
		<div class="col-md-12">
			<h1 class="margin-bottom-15">重置密码</h1>
			<form class="form-horizontal templatemo-forgot-password-form templatemo-container" role="form" action="#" method="post">
				<div class="form-group">
		          <div class="col-md-12">
		          	请输入您在我们网站注册的电子邮件地址。
		          </div>
		        </div>
		        <div class="form-group">
		          <div class="col-md-12">
		            <input type="text" class="form-control" id="email" placeholder="Your email">
		          </div>
		        </div>
		        <div class="form-group">
		          <div class="col-md-12">
		            <input type="submit" value="Submit" class="btn btn-danger">
                    <br><br>
                    <a href="{{ url_for("student.login") }}">login</a>
		          </div>
		        </div>
		      </form>
		</div>
	</div>
</body>
</html>

app/templates/student/login.html
<!DOCTYPE html>
<head>
    <title>login</title>
    <meta name="keywords" content=""/>
    <meta name="description" content=""/>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="{{ url_for('static',filename="student/css/font-awesome.min.css") }}" rel="stylesheet" type="text/css">
    <link href="{{ url_for('static',filename="student/css/bootstrap.min.css") }}" rel="stylesheet" type="text/css">
    <link href="{{ url_for('static',filename="student/css/bootstrap-theme.min.css") }}" rel="stylesheet"
          type="text/css">
    <link href="{{ url_for('static',filename="student/css/templatemo_style.css") }}" rel="stylesheet" type="text/css">

</head>
<body class="templatemo-bg-gray">
<div class="container">
    <div class="col-md-12">
        <h1 class="margin-bottom-15">登录</h1>





        <form class="form-horizontal templatemo-container templatemo-login-form-1 margin-bottom-30" role="form"
              method="post" action="/login/">
            <div class="form-group">
                <div class="col-xs-12">
                    <div class="control-wrapper">
                        <label for="username" class="control-label fa-label"><i class="fa fa-user fa-medium"></i></label>
                        用户名：{{ form.username }}
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-12">
                    <div class="control-wrapper">
                        <label for="password" class="control-label fa-label"><i class="fa fa-lock fa-medium"></i></label>
                        密&nbsp;&nbsp;码：{{ form.pwd }}
                    </div>
                </div>
            </div>

            {% if error_message %}
                <p class="login-box-msg" style="color:red;">{{ error_message }}</p>
            {% endif %}

            <div class="form-group">
                <div class="col-md-12">
                    <div class="checkbox control-wrapper">
                        <label>
                            <input type="checkbox"> 记住我
                        </label>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-12">
                    <div class="control-wrapper">
                        {{ form.submit }}
                        <a href="forgot-password.html" class="text-right pull-right">忘记密码?</a>
                    </div>
                </div>
            </div>
            <hr>
        </form>
        <div class="text-center">
            <a href="{{ url_for('student.register') }}" class="templatemo-create-new"> 新用户注册 <i
                    class="fa fa-arrow-circle-o-right"></i></a>
        </div>
    </div>
</div>
</body>
</html>

app/templates/student/register2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h2>注册页面</h2>
    <form action="">
        <p><label for="username">用户名：</label><input type="text" name="uname" id="username"/></p>
        <p><label for="pwd">密码：</label><input type="password" name="pwd" id="pwd" /></p>
        <p><input type="submit" value="注册"/></p>
    </form>
</body>
    <script src="{{ url_for('static',filename="student/js/jquery-1.11.1.min.js") }}"></script>
    <script>
        //使用jQuery，获取用户名输入框信息，触发焦点事件
        //ajax_get请求校验方式
        $("#username").blur(
            function () {
                //获取用户名输入框输入的用户名，并将其拼接到url上，用于ajax get请求
                var username = $("#username").val();
                var url = "/userValid/?username="+username;
                $.ajax(
                    {
                        url: url,
                        type: "get",
                        data: "",
                        success: function (data) {
                            if (data.code == 400){//400代表用户名已存在，submit失效
                                $("#submit").attr("disabled",true)
                            } else{//否则submit正常
                                $("#submit").attr("disabled",false)
                            }
                            //将后面传递过来的json数据打印到前端，提示用户
                            $("#message").text(data.data)
                        },
                        error: function (error) {
                            console.log(error)
                        }
                    }
                )
            }
        );

        //ajax_post请求校验方式

        $("#username").blur(
            function () {
                var username = $("#username").val();
                var url = "/userValid/";
                var send_data = {
                    "username": username,
                    "csrf_token": '{{ csrf_token() }}'
                };
                $.ajax(
                    {
                        url: url,
                        type: "post",
                        data: send_data,
                        success: function (data) {
                            if (data.code == 400){
                                $("#submit").attr("disabled",true)
                            } else{
                                $("#submit").attr("disabled",false)
                            }
                            $("#message").text(data.data)
                        },
                        error: function (error) {
                            console.log(error)
                        }
                    }
                )
            }
        );

    </script>

</html>

app/templates/student/register_ok.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>register_ok</title>
</head>
<body>
<p>注册成功，点击<a href="{{ url_for('student.login') }}">登录</a>跳转到登陆页面</p>
</body>
</html>

app/templates/student/sign.html
{# 导入分页宏 #}
{% import "page.html" as pg %}

<!doctype html>
<html class="no-js">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>sign table</title>
    <meta name="description" content="这是一个 签到table 页面">
    <meta name="keywords" content="table">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <meta name="renderer" content="webkit">
    {#  <meta http-equiv="Cache-Control" content="no-siteapp" />#}
    <link rel="icon" type="image/png" href="{{ url_for('static',filename="student/assets/i/favicon.png") }}">
    <link rel="apple-touch-icon-precomposed"
          href="{{ url_for('static',filename="student/assets/i/app-icon72x72@2x.png") }}">
    <meta name="apple-mobile-web-app-title" content="Amaze UI"/>
    <link rel="stylesheet" href="{{ url_for('static',filename="student/assets/css/amazeui.min.css") }}"/>
    <link rel="stylesheet" href="{{ url_for('static',filename="student/assets/css/admin.css") }}">
</head>
<body>

<header class="am-topbar admin-header">
    <div class="am-topbar-brand">
        <strong>签到</strong>
        <small>sign</small>
    </div>

    <button class="am-topbar-btn am-topbar-toggle am-btn am-btn-sm am-btn-success am-show-sm-only"
            data-am-collapse="{target: '#topbar-collapse'}"><span class="am-sr-only">导航切换</span> <span
            class="am-icon-bars"></span></button>

    <div class="am-collapse am-topbar-collapse" id="topbar-collapse">

        <ul class="am-nav am-nav-pills am-topbar-nav am-topbar-right admin-header-list">
            <li class="am-dropdown" data-am-dropdown>
                <a class="am-dropdown-toggle" data-am-dropdown-toggle href="javascript:;">
                    <span class="am-icon-users"></span> {{ session.get("username") }} <span
                        class="am-icon-caret-down"></span>
                </a>
                <ul class="am-dropdown-content">
                    <li><a href="#"><span class="am-icon-user"></span> 资料</a></li>
                    <li><a href="#"><span class="am-icon-cog"></span> 设置</a></li>
                    <li><a href="{{ url_for('student.logout') }}"><span class="am-icon-power-off"></span> 退出</a></li>
                </ul>
            </li>
        </ul>
    </div>
</header>

<div class="am-cf admin-main">
    <!-- 边注栏开始 -->
    <div class="admin-sidebar">
        <ul class="am-list admin-sidebar-list">
            <li><a href=""><span class="am-icon-home"></span> 首页</a></li>
            <li><a href="" class="am-cf"><span class="am-icon-check"></span> 个人资料<span
                    class="am-icon-star am-fr am-margin-right admin-icon-yellow"></span></a></li>
            <li><a href="{{ url_for('student.logout') }}"><span class="am-icon-sign-out"></span> 注销</a></li>

        </ul>

        <div class="am-panel am-panel-default admin-sidebar-panel">
            <div class="am-panel-bd">
                <p><span class="am-icon-bookmark"></span> 心語 </p>
                <p>時光靜好，與君語；細水流年，與君同。</p>
            </div>
        </div>

        <div class="am-panel am-panel-default admin-sidebar-panel">
            <div class="am-panel-bd">
                <p><span class="am-icon-tag"></span> 加油吧，少年！ </p>
                <p>每一個讓你難堪的現在</p>
                <p>都有一個不夠努力的曾經</p>
            </div>
        </div>
        <br/>
        <br/>
        <br/>
        <br/>
        <br/>
        <br/>
        <br/>
        <br/>
        <br/>
        <br/>
        <br/>
        <br/>
        <br/>
        <br/>
        <br/>

    </div>
    <!-- 边注栏结束 -->

    <!-- 内容开始 -->
    <div class="admin-content">

        <div class="am-cf am-padding">
            <div class="am-fl am-cf">
                <strong class="am-text-primary am-text-lg">签到</strong> /
                <small>sign</small>
            </div>
        </div>

        <div class="am-g">
            <div class="am-u-md-6 am-cf">
                <div class="am-fl am-cf">
                    <div class="am-btn-toolbar am-fl">
                    </div>
                </div>
            </div>
            <div class="am-u-md-3 am-cf">
                <div class="am-fr">
                </div>
            </div>
        </div>

        <div class="am-g">
            <div class="am-u-sm-12">
                {# *** 表单开始 ** #}
                <form class="am-form" method="post" action="/sign/">

                    <table class="am-table am-table-striped am-table-hover table-main">
                        <thead>
                        <tr>
                            <th class="table-id">学号</th>
                            <th class="table-name">姓名</th>
                            <th class="table-cls">班级</th>
                            <th class="table-date">日期</th>
                            <th class="table-unit">章节</th>
                            <th class="table-v_num">视频号</th>
                            <th class="table-code_num">代码（行）</th>
                            <th class="table-set">操作</th>
                        </tr>
                        </thead>

                        <tbody>
                        <tr>
                            <td>{{ user.id }}</td>
                            <td>{{ user.name }}</td>
                            <td>{{ user.cls.name }}</td>


                                {% if sign and sign[0].datetime.date().strftime("%Y-%m-%d")==datetime[:10] %}

                                    <td>{{ sign[0].datetime }}</td>
                                    <td>{{ sign[0].unit }}</td>
                                    <td>{{ sign[0].v_num }}</td>
                                    <td>{{ sign[0].code_num }}</td>
                                    <td>
                                    <div class="am-btn-toolbar">
                                        <div class="am-btn-group am-btn-group-xs">已签到</div>
                                    </div>
                                    </td>
                                {% else %}
                                    <td>{{ datetime }}</td>
                                    <td class="form_td_sign">{{ form.unit }}</td>
                                    <td class="form_td_sign">{{ form.v_num }}</td>
                                    <td class="form_td_sign">{{ form.code_num }}</td>
                                    <td>
                                    <div class="am-btn-toolbar">
                                        <div class="am-btn-group am-btn-group-xs">
                                            <input type="submit"
                                                   class="am-btn am-btn-default am-btn-xs am-text-secondary" value="签到"
                                                   onclick="">
                                        </div>
                                    </div>
                                    </td>
                                {% endif %}
                        </tr>
                        </tbody>
                    </table>

                    <table class="am-table am-table-striped am-table-hover table-main">
                        <h4>历史签到</h4>
                        <thead>
                        <tr>
                            <th class="table-id">编号</th>
                            <th class="table-id">学号</th>
                            <th class="table-name">姓名</th>
                            <th class="table-cls">班级</th>
                            <th class="table-date">日期</th>
                            <th class="table-unit">章节</th>
                            <th class="table-v_num">视频号</th>
                            <th class="table-code_num">代码（行）</th>
                            <th class="table-set">操作</th>
                        </tr>
                        </thead>

                        <tbody>
                        {% if sign %}
                            {% for i in pager.items %}
                                <tr>
                                    <td>{{ loop.index }}</td>
                                    <td>{{ i.sid }}</td>
                                    <td>{{ user.name }}</td>
                                    <td>{{ user.cls.name }}</td>
                                    <td>{{ i.datetime }}</td>
                                    <td>{{ i.unit }}</td>
                                    <td>{{ i.v_num }}</td>
                                    <td>{{ i.code_num }}</td>
                                    <td>
                                        <div class="am-btn-toolbar">
                                            <div class="am-btn-group am-btn-group-xs">已签到</div>
                                        </div>
                                    </td>
                                </tr>
                            {% endfor %}
                        {% endif %}

                        </tbody>
                    </table>
                    <div class="am-cf">
                        共  {{ sign_count }}  条记录,当前第  {{ pager.page }}  页
                        <div class="am-fr">
                            {{ pg.pager(pager, 'student.sign') }}
                        </div>
                    </div>
                    <hr/>


                </form>
                {# ** 表单结束 ** #}
            </div>

        </div>
    </div>
    <!-- 内容结束 -->
</div>

<!-- 页面底部 -->
<footer>
    <hr>
    <p class="am-padding-left">© by.@zwm 网站许可.</p>
</footer>

<!--[if (gte IE 9)|!(IE)]><!-->
<script src="{{ url_for('static',filename="student/assets/js/jquery.min.js") }}"></script>
<script src="{{ url_for('static',filename="student/assets/js/amazeui.min.js") }}"></script>
<!--<![endif]-->
<script src="{{ url_for('static',filename="student/assets/js/app.js") }}"></script>

{#    新增样式#}
<script src="{{ url_for('static',filename="student/js/jquery-1.11.1.min.js") }}"></script>
<script>
        {#function sign() {#}
        {#    var form_td_sign= document.getElementsByClassName('form-control');#}
        {##}
        {#    for (var i = 0; i < form_td_sign.length; i++) {#}
        {#        if (!trim(form_td_sign[i].value)) {#}
        {#            form_td_sign[i].focus();#}
        {#            alert('签到失败！请检查信息是否填写正确！');#}
        {#            return false;#}
        {#        }#}
        {#    }#}
        {#    alert('签到成功！');#}
        {#    return true;#}

</script>
{#    新增样式结束#}
</body>
</html>