app/teacher/forms.py
from flask_wtf import FlaskForm     # FlaskForm为表单基类
from wtforms.fields import SubmitField, StringField, PasswordField, SelectField, DateField, RadioField
from wtforms.validators import DataRequired, EqualTo, Email, Regexp, ValidationError, InputRequired
from app.models import Teacher


class LoginForm(FlaskForm):
    username = StringField(
        label="用户名",
        validators=[
            DataRequired("请输入用户名！")
        ],
        description="用户名",
        render_kw={
            "class": "form-control",
            "id": "username",
            "placeholder": "请输入用户名！",
            "required": 'required',  # 表示此项不能为空
            "autofocus": "autofocus",
        }
    )
    password = PasswordField(
        label="密码",
        validators=[
            DataRequired("请输入密码！")
        ],
        description="密码",
        render_kw={
            "class": "form-control",
            "id": "password",
            "placeholder": "请输入密码！",
            "required": 'required',  # 表示此项不能为空
            "autofocus": "autofocus",
        }
    )
    submit = SubmitField(
        '登录',
        render_kw={
            "class": "btn btn-info",
        }
    )


class RegisterForm(FlaskForm):
    username = StringField(
        label="用户名",
        validators=[
            InputRequired(message="请输入用户名！"),
        ],
        description="用户名",
        render_kw={
            "class": "form-control",
            "placeholder": "请输入用户名！",
            "required": 'required',  # 表示此项不能为空
            "autofocus": "autofocus",
        }
    )
    name = StringField(
        label="姓名",
        validators=[InputRequired(message="请输入姓名！")],
        description="姓名",
        render_kw={
            "class": "form-control",
            "placeholder": "请输入姓名！",
            "required": 'required',  # 表示此项不能为空
            "autofocus": "autofocus",
        }
    )
    pwd = PasswordField(
        label="密码",
        validators=[InputRequired(message="请输入密码！")],
        description="密码",
        render_kw={
            "class": "form-control",
            "placeholder": "请输入密码！",
            "required": 'required',  # 表示此项不能为空
            "autofocus": "autofocus",
        }
    )
    repwd = PasswordField(
        label="确认密码",
        validators=[InputRequired(message="请输入确认密码！"), EqualTo('pwd', message="两次密码不一致！")],
        description="确认密码",
        render_kw={
            "class": "form-control",
            "placeholder": "请输入确认密码！",
            "required": 'required',  # 表示此项不能为空
            "autofocus": "autofocus",
        }
    )
    email = StringField(
        label="邮箱",
        validators=[InputRequired(message="请输入邮箱！"), Email(message="邮箱格式不正确！")],
        description="邮箱",
        render_kw={
            "class": "form-control",
            "placeholder": "请输入邮箱！",
            "required": 'required',  # 表示此项不能为空
            "autofocus": "autofocus",
        }
    )
    phone = StringField(
        label="手机号码",
        validators=[InputRequired(message="请输入手机号码！"), Regexp("1[3589]\\d{9}", message="手机号码格式不正确！")],
        description="手机号码",
        render_kw={
            "class": "form-control",
            "placeholder": "请输入手机号码！",
            "required": 'required',  # 表示此项不能为空
            "autofocus": "autofocus",
        }
    )

    def validate_name(self, field):
        username = field.data
        user = Teacher.query.filter_by(username=username).count()
        if user == 1:
            raise ValidationError("用户名已经存在！")

    def validate_email(self, field):
        email = field.data
        user = Teacher.query.filter_by(email=email).count()
        if user == 1:
            raise ValidationError("邮箱已经存在！")

    def validate_phone(self, field):
        phone = field.data
        user = Teacher.query.filter_by(phone=phone).count()
        if user == 1:
            raise ValidationError("手机号码已经存在！")


class GetSignsForm(FlaskForm):
    pass

app/teacher/__init__.py
from flask import Blueprint

teacher = Blueprint("teacher", __name__)

import app.teacher.views

app/teacher/views.py
from functools import wraps
from flask import render_template, redirect, url_for, session, request, jsonify
from werkzeug.security import generate_password_hash
from wtforms.validators import ValidationError

from . import teacher
from app import db, app
from app.models import Teacher, Class, Sign, Student
from app.teacher.forms import LoginForm, GetSignsForm, RegisterForm


# 登陆装饰器
def user_login_req(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if 'username' not in session:
            return redirect(url_for("teacher.login", next=request.url))
        return f(*args, **kwargs)

    return decorated_function


@teacher.route('/')
def hello_world():
    return render_template('teacher/teacher-welcome.html')


@teacher.route('/login/', methods=["GET", "POST"])
def login():
    form = LoginForm()
    # 通过session获取 error_message
    error_message = session.get('error_message')
    session["error_message"] = None

    if request.method == "POST":
        data = form.data
        user = Teacher.query.filter_by(username=data["username"]).first()

        if not user:
            error_message = "用户名不存在！"
            session["error_message"] = error_message
            return redirect(url_for("teacher.login"))
        if not user.check_pwd(data["password"]):
            error_message = "密码错误！"
            session["error_message"] = error_message
            return redirect(url_for("teacher.login"))

        session["username"] = user.username

        return redirect(url_for("teacher.index"))

    return render_template("teacher/login.html", form=form, error_message=error_message)


@teacher.route('/logout/')
def logout():
    session["username"] = None
    return redirect(url_for("teacher.login"))


@teacher.route('/register/', methods=["GET", "POST"])
def register():
    if request.method == "GET":
        form = RegisterForm()
        return render_template("teacher/register.html", form=form, err=None, err2=None)
    elif request.method == "POST":
        # 获取数据
        form = RegisterForm(request.form)
        try:
            form.validate_name(form.username)
            form.validate_email(form.email)
            form.validate_phone(form.phone)
        except ValidationError as e:
            return render_template("teacher/register.html", form=form, err=None, err2=e)

        if form.validate():
            data = form.data

            teacher = Teacher(
                username=data["username"],
                name=data["name"],
                pwd=generate_password_hash(data["pwd"]),
                email=data["email"],
                phone=data["phone"],
            )
            db.session.add(teacher)
            db.session.commit()

            session["username"] = teacher.username
            session["password"] = teacher.pwd
            return render_template("teacher/register_ok.html")
        err = form.errors
        return render_template("teacher/register.html", form=form, err=err, err2=None)


@teacher.route('/index/')
@user_login_req
def index():
    return render_template('teacher/index.html')


@teacher.route('/get_signs/', methods=["GET", "POST"])
@user_login_req
def get_signs():
    signs = Sign.query.with_entities(Sign.sid.label('sid'), Student.name.label('sname'), Class.name.label('cname'),
                                     Sign.datetime.label('datetime'), Sign.unit.label('unit'),
                                     Sign.v_num.label('v_num'), Sign.code_num.label('code_num')) \
        .join(Student, Sign.sid == Student.id).join(Class, Student.cid == Class.id).all()
    return render_template("teacher/get_signs.html", signs=signs)


@teacher.route('/search_sign/', methods=['POST'])
def search_sign():
    cname = request.form.get('cname')
    sname = request.form.get('sname')
    time = request.form.get('create_time')
    signs = Sign.query.with_entities(Sign.sid.label('sid'), Student.name.label('sname'), Class.name.label('cname'),
                                     Sign.datetime.label('datetime'), Sign.unit.label('unit'),
                                     Sign.v_num.label('v_num'), Sign.code_num.label('code_num')) \
        .join(Student, Sign.sid == Student.id).join(Class, Student.cid == Class.id)

    if time:
        signs = signs.filter(Sign.datetime.like(time + "%"))
    if sname:
        signs = signs.filter(Student.name == sname)
    if cname:
        signs = signs.filter(Class.name == cname)
    data = signs.all()
    datas = []
    for d in data:
        datas.append({
            'sid': d.sid,
            'sname': d.sname,
            'cname': d.cname,
            'datetime': str(d.datetime)[:11] if d.datetime else "",
            'unit': d.unit,
            'v_num': d.v_num,
            'code_num': d.code_num,
        })
    return jsonify({'data': datas})

app/templates/teacher/get_signs.html
{% extends "common/index_for_inner.html" %}

{% block block_title_content %}学生签到页{% endblock %}

{% block block_content %}
    <div class="admin-content">

        <div class="am-cf am-padding">
            <div class="am-fl am-cf"><strong class="am-text-primary am-text-lg">学生签到记录</strong> /
                <small>Table</small>
            </div>
        </div>

        <div class="content-row">
            <form>
{#                <div class="form-group col-md-3">#}
                <div class="am-form-group am-margin-left am-fl">
                    <input id="cname" type="text" class="form-control" placeholder="班级">
                </div>
{#                <div class="form-group col-md-3">#}
                <div class="am-form-group am-margin-left am-fl">
                    <input id="sname" type="text" class="form-control" placeholder="姓名">
                </div>
{#                <div class="form-group col-md-3">#}
                <div class="am-form-group am-margin-left am-fl">
                    <input id="create_time" type="date" class="form-control" placeholder="日期">
                </div>
                <div class="am-form-group am-margin-left am-fl">
                    <input type="button" class="btn btn-primary" value="查 询" onclick="do_search()">
                    <input id="reset" type="button" class="btn btn-info" value="重 置">
                </div>
            </form>
        </div>

        <div class="am-g">
            <div class="am-u-sm-12">
                <form class="am-form">
                    <table id="info" class="am-table am-table-striped am-table-hover table-main">
                        <thead>
                        <tr>
                            <th class="table-id">编号</th>
                            <th class="table-id">学号</th>
                            <th class="table-name">姓名</th>
                            <th class="table-cls">班级</th>
                            <th class="table-date">日期</th>
                            <th class="table-unit">章节</th>
                            <th class="table-v_num">视频号</th>
                            <th class="table-code_num">代码（行）</th>
                            <th class="table-set">操作</th>
                        </tr>
                        </thead>
                        <tbody id="form-tbody">
                        {#                            {% if sign %}#}
                        {#                            {% for i in sign %}#}
                        {#                                <tr>#}
                        {#                                    <td>{{ loop.index }}</td>#}
                        {#                                    <td>{{ i.sid }}</td>#}
                        {#                                    <td>{{ user.name }}</td>#}
                        {#                                    <td>{{ user.cls.name }}</td>#}
                        {#                                    <td>{{ i.datetime }}</td>#}
                        {#                                    <td>{{ i.unit }}</td>#}
                        {#                                    <td>{{ i.v_num }}</td>#}
                        {#                                    <td>{{ i.code_num }}</td>#}
                        {#                                    <td>#}
                        {#                                        <div class="am-btn-toolbar">#}
                        {#                                            <div class="am-btn-group am-btn-group-xs">已签到</div>#}
                        {#                                        </div>#}
                        {#                                    </td>#}
                        {#                                </tr>#}
                        {#                            {% endfor %}#}
                        {#                        {% endif %}#}

                        </tbody>
                    </table>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block block_new_script %}
    <script src="{{ url_for('static',filename="student/assets/css/site.min.css") }}"></script>
    <script>

        $(function () {
            init_data();
            $('#reset').click(reset)
        });

        function init_data() {
            var csrftoken = $("meta[name=csrf-token]").attr("content");
            $.ajax({
                url: '/teacher/search_sign/',
                method: 'POST',
                headers: {"X-CSRFToken": csrftoken},
                success: function (e) {
                    var str = '';
                    for (var i = 0; i < e['data'].length; i++) {

                        var qd = e['data'][i];
                        str += '<tr><td>' + i + '</td><td>' + qd['sid'] + '</td><td>' + qd['sname'] + '</td><td>' + qd['cname'] + '</td><td>' + qd['datetime'] + '</td><td>' + qd['unit'] + '</td><td>' + qd['v_num'] + '</td><td>' + qd['code_num'] + '</td><td>' + '已签到' + '</td></tr>'

                    }

                    $("#info").append(str)
                }
            })
        }

        function do_search() {
            var csrftoken = $("meta[name=csrf-token]").attr("content");

            var cname = $('#cname').val();
            var sname = $('#sname').val();
            var create_time = $('#create_time').val();
            var th = '<tr>' + $('#info').children()[0].children[0].innerHTML + '</tr>';
            $.ajax({
                url: '/teacher/search_sign/',
                method: 'POST',
                data: {'cname': cname, 'sname': sname, 'create_time': create_time},
                headers: {"X-CSRFToken": csrftoken},
                success: function (e) {
                    var str = '';
                    for (var i = 0; i < e['data'].length; i++) {
                        var qd = e['data'][i];
                        str += '<tr><td>' + i + '</td><td>' + qd['sid'] + '</td><td>' + qd['sname'] + '</td><td>' + qd['cname'] + '</td><td>' + qd['datetime'] + '</td><td>' + qd['unit'] + '</td><td>' + qd['v_num'] + '</td><td>' + qd['code_num'] + '</td><td>' + '已签到' + '</td></tr>'
                    }

                    $('#info tr').remove();
                    console.log(th + str);
                    $('#info').append(th + str);
                    {#$('#info').append(str)#}


                }
            })
        }

        function reset() {
            $('#cname').val('');
            $('#sname').val('');
            $('#create_time').val('')
        }

    </script>

{% endblock %}

app/templates/teacher/index.html
{% extends "common/index_for_login.html" %}

{% block block_title_content %}首页{% endblock %}

{% block block_content %}
    <div class="admin-content">

        <div class="am-cf am-padding">
            <div class="am-fl am-cf"><strong class="am-text-primary am-text-lg">首页</strong> /
                <small>一些常用模块</small>
            </div>
        </div>

        <ul class="am-avg-sm-1 am-avg-md-4 am-margin am-padding am-text-center admin-content-list ">
            <li><a href="#" class="am-text-success"><span class="am-icon-btn am-icon-file-text"></span><br/>新增签到<br/>100</a>
            </li>
            <li><a href="#" class="am-text-warning"><span class="am-icon-btn am-icon-briefcase"></span><br/>功能2<br/>100</a>
            </li>
            <li><a href="#" class="am-text-danger"><span class="am-icon-btn am-icon-recycle"></span><br/>功能3<br/>82</a>
            </li>
            <li><a href="#" class="am-text-secondary"><span class="am-icon-btn am-icon-user-md"></span><br/>功能4<br/>300</a>
            </li>
        </ul>

        <div class="am-g">
            <div class="am-u-sm-12">
                <h3 style="color: #0c7cb5">最新签到</h3>
                <table class="am-table am-table-bd am-table-striped admin-content-table">
                    <thead>
                    <tr>
                        <th>编号</th>
                        <th>学号</th>
                        <th>姓名</th>
                        <th>签到时间</th>
                        <th>代码量</th>
                        <th>操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td>1</td>
                        <td>11</td>
                        <td>John Clark</td>
                        <td>2018-10-17</td>
                        <td>100</td>
                        <td>
                            <div class="am-dropdown" data-am-dropdown>
                                <button class="am-btn am-btn-default am-btn-xs am-dropdown-toggle"
                                        data-am-dropdown-toggle><span class="am-icon-cog"></span> <span
                                        class="am-icon-caret-down"></span></button>
                                <ul class="am-dropdown-content">
                                    <li><a href="#">查看详情</a></li>
                                    <li><a href="#">操作2</a></li>
                                    <li><a href="#">操作3</a></li>
                                </ul>
                            </div>
                        </td>
                    </tr>
                                        <tr>
                        <td>1</td>
                        <td>11</td>
                        <td>John Clark</td>
                        <td>2018-10-17</td>
                        <td>100</td>
                        <td>
                            <div class="am-dropdown" data-am-dropdown>
                                <button class="am-btn am-btn-default am-btn-xs am-dropdown-toggle"
                                        data-am-dropdown-toggle><span class="am-icon-cog"></span> <span
                                        class="am-icon-caret-down"></span></button>
                                <ul class="am-dropdown-content">
                                    <li><a href="#">查看详情</a></li>
                                    <li><a href="#">操作2</a></li>
                                    <li><a href="#">操作3</a></li>
                                </ul>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td>1</td>
                        <td>11</td>
                        <td>John Clark</td>
                        <td>2018-10-17</td>
                        <td>100</td>
                        <td>
                            <div class="am-dropdown" data-am-dropdown>
                                <button class="am-btn am-btn-default am-btn-xs am-dropdown-toggle"
                                        data-am-dropdown-toggle><span class="am-icon-cog"></span> <span
                                        class="am-icon-caret-down"></span></button>
                                <ul class="am-dropdown-content">
                                    <li><a href="#">查看详情</a></li>
                                    <li><a href="#">操作2</a></li>
                                    <li><a href="#">操作3</a></li>
                                </ul>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td>1</td>
                        <td>11</td>
                        <td>John Clark</td>
                        <td>2018-10-17</td>
                        <td>100</td>
                        <td>
                            <div class="am-dropdown" data-am-dropdown>
                                <button class="am-btn am-btn-default am-btn-xs am-dropdown-toggle"
                                        data-am-dropdown-toggle><span class="am-icon-cog"></span> <span
                                        class="am-icon-caret-down"></span></button>
                                <ul class="am-dropdown-content">
                                    <li><a href="#">查看详情</a></li>
                                    <li><a href="#">操作2</a></li>
                                    <li><a href="#">操作3</a></li>
                                </ul>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td>1</td>
                        <td>11</td>
                        <td>John Clark</td>
                        <td>2018-10-17</td>
                        <td>100</td>
                        <td>
                            <div class="am-dropdown" data-am-dropdown>
                                <button class="am-btn am-btn-default am-btn-xs am-dropdown-toggle"
                                        data-am-dropdown-toggle><span class="am-icon-cog"></span> <span
                                        class="am-icon-caret-down"></span></button>
                                <ul class="am-dropdown-content">
                                    <li><a href="#">查看详情</a></li>
                                    <li><a href="#">操作2</a></li>
                                    <li><a href="#">操作3</a></li>
                                </ul>
                            </div>
                        </td>
                    </tr>

                    </tbody>
                </table>
            </div>
        </div>

        <div class="am-g">
            <div class="am-u-md-6">
                <div class="am-panel am-panel-default">
                    <div class="am-panel-hd am-cf" data-am-collapse="{target: '#collapse-panel-1'}">文件上传<span
                            class="am-icon-chevron-down am-fr"></span></div>
                    <div class="am-panel-bd am-collapse am-in" id="collapse-panel-1">
                        <ul class="am-list admin-content-file">
                            <li>
                                <strong><span class="am-icon-upload"></span> Kong-cetian.Mp3</strong>
                                <p>3.3 of 5MB - 5 mins - 1MB/Sec</p>
                                <div class="am-progress am-progress-striped am-progress-sm am-active">
                                    <div class="am-progress-bar am-progress-bar-success" style="width: 82%">82%</div>
                                </div>
                            </li>
                            <li>
                                <strong><span class="am-icon-check"></span> 好人-cetian.Mp3</strong>
                                <p>3.3 of 5MB - 5 mins - 3MB/Sec</p>
                            </li>
                            <li>
                                <strong><span class="am-icon-check"></span> 其实都没有.Mp3</strong>
                                <p>3.3 of 5MB - 5 mins - 3MB/Sec</p>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="am-panel am-panel-default">
                    <div class="am-panel-hd am-cf" data-am-collapse="{target: '#collapse-panel-2'}">学生学习进度分析<span
                            class="am-icon-chevron-down am-fr"></span></div>
                    <div id="collapse-panel-2" class="am-in">
                        <hr>
                        <hr>
                        <hr>
                        给这来张统计图
                        <hr>
                        <hr>
                        <hr>
                    </div>
                </div>
            </div>

            <div class="am-u-md-6">
                <div class="am-panel am-panel-default">
                    <div class="am-panel-hd am-cf" data-am-collapse="{target: '#collapse-panel-4'}">任务 task<span
                            class="am-icon-chevron-down am-fr"></span></div>
                    <div id="collapse-panel-4" class="am-panel-bd am-collapse am-in">
                        <ul class="am-list admin-content-task">
                            <li>
                                <div class="admin-task-meta"> Posted on 25/1/2120 by John Clark</div>
                                <div class="admin-task-bd">
                                    任务1
                                </div>
                                <div class="am-cf">
                                    <div class="am-btn-toolbar am-fl">
                                        <div class="am-btn-group am-btn-group-xs">
                                            <button type="button" class="am-btn am-btn-default"><span
                                                    class="am-icon-check"></span></button>
                                            <button type="button" class="am-btn am-btn-default"><span
                                                    class="am-icon-pencil"></span></button>
                                            <button type="button" class="am-btn am-btn-default"><span
                                                    class="am-icon-times"></span></button>
                                        </div>
                                    </div>
                                    <div class="am-fr">
                                        <button type="button" class="am-btn am-btn-default am-btn-xs">删除</button>
                                    </div>
                                </div>
                            </li>
                            <li>
                                <div class="admin-task-meta"> Posted on 25/1/2120 by 呵呵呵</div>
                                <div class="admin-task-bd">
                                    任务2
                                </div>
                                <div class="am-cf">
                                    <div class="am-btn-toolbar am-fl">
                                        <div class="am-btn-group am-btn-group-xs">
                                            <button type="button" class="am-btn am-btn-default"><span
                                                    class="am-icon-check"></span></button>
                                            <button type="button" class="am-btn am-btn-default"><span
                                                    class="am-icon-pencil"></span></button>
                                            <button type="button" class="am-btn am-btn-default"><span
                                                    class="am-icon-times"></span></button>
                                        </div>
                                    </div>
                                    <div class="am-fr">
                                        <button type="button" class="am-btn am-btn-default am-btn-xs">删除</button>
                                    </div>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>

            </div>
        </div>
    </div>
{% endblock %}

app/templates/teacher/login.html
{% extends "common/index_for_login.html" %}
{% block block_title %}login{% endblock %}

{% block block_link %}
    <link href="{{ url_for('static',filename="student/css/font-awesome.min.css") }}" rel="stylesheet" type="text/css">
    <link href="{{ url_for('static',filename="student/css/bootstrap.min.css") }}" rel="stylesheet" type="text/css">
    <link href="{{ url_for('static',filename="student/css/bootstrap-theme.min.css") }}" rel="stylesheet" type="text/css">
    <link href="{{ url_for('static',filename="student/css/templatemo_style.css") }}" rel="stylesheet" type="text/css">
{% endblock %}

{% block block_body_h1 %}
        <h1 class="margin-bottom-15">登录--Teacher</h1>
{% endblock %}


{% block block_body_inner_container %}
        <form class="form-horizontal templatemo-container templatemo-login-form-1 margin-bottom-30" role="form"
              method="post" action="/teacher/login/">
            <div class="form-group">
                <div class="col-xs-12">
                    <div class="control-wrapper">
                        <label for="username" class="control-label fa-label"><i class="fa fa-user fa-medium"></i></label>
                        用户名：{{ form.username }}
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-12">
                    <div class="control-wrapper">
                        <label for="password" class="control-label fa-label"><i class="fa fa-lock fa-medium"></i></label>
                        密&nbsp;&nbsp;码：{{ form.password }}
                    </div>
                </div>
            </div>

            {% if error_message %}
                <p class="login-box-msg" style="color:red;">{{ error_message }}</p>
            {% endif %}


            <div class="form-group">
                <div class="col-md-12">
                    <div class="checkbox control-wrapper">
                        <label>
                            <input type="checkbox"> 记住我
                        </label>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-12">
                    <div class="control-wrapper">
                        {{ form.submit }}
                        <a href="#" class="text-right pull-right">忘记密码?</a>
                    </div>
                </div>
            </div>
            <hr>
        </form>
        <div class="text-center">
            <a href="{{ url_for('teacher.register') }}" class="templatemo-create-new"> 新用户注册 <i
                    class="fa fa-arrow-circle-o-right"></i></a>
        </div>
{% endblock %}

app/templates/teacher/register_ok.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>register_ok</title>
</head>
<body>
<p>注册成功，点击<a href="{{ url_for('teacher.login') }}">登录</a>跳转到登陆页面</p>
</body>
</html>

app/templates/teacher/teacher-welcome.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Teacher-welcome</title>
    <script>
        function  changeclk() {
            document.body.style.backgroundImage = "url(../../static/images/welcome-teacher.jpg)";
        }
    </script>
</head>
<body>
    <div class="div1" id="div_1">
        <p>Teacher</p>
        <h2>欢迎使用XX学生签到系统</h2>
        <input type="button" value="是"  onclick="changeclk()"/>
        <input type="button" value="否"  onmouseover="chengove()"/>
    </div>
</body>
</html>